<?php
namespace Admin\Controller;
use Think\Controller;
class AboutUsController extends CommonController{
	public function left(){
		$this->display();
	}
	//================================================================
	//公司简介
	public function company_introduce(){
		$company_introduceM=D('company_introduce');
		$company_introduce_res=$company_introduceM->select();
		$this->assign('company_introduce_res',$company_introduce_res);
		//查询包含的导航信息
		$navM=D('nav');
		$navarr=array();
		for($i=0;$i<count($company_introduce_res);$i++){
            $whereAA['nav_id']=$company_introduce_res[$i]['nav_id'];
            $navres=$navM->where($whereAA)->find();
            $navarr[]=$navres;
		}
		$this->assign('navarr',$navarr);
		$this->display();
	}
	//================================================================
	//公司简介添加
	public function company_introduce_add(){
		if($_POST){
			$company_introduceM=D('company_introduce');
			$whereci['ci_id']=1;
			$selres=$company_introduceM->where($whereci)->find();
			$data['ci_name']=I('post.ci_name');
			$data['ci_content']=I('post.ci_content','',false);
			$data['ci_content_english']=I('post.ci_content_english','',false);
			$data['ci_logo']=I('post.ci_logo');
			$data['ci_year']=I('post.ci_year');
			$data['ci_url']=I('post.ci_url');
			$data['ci_logotitle']=I('post.ci_logotitle');
			
			$data['ci_logotitle_english']=I('post.ci_logotitle_english');
			$data['nav_id']=I('post.nav_id');
			
			if($selres){
                $addres=$company_introduceM->where($whereci)->save($data);
			}else{
				$data['ci_id']=1;
				$addres=$company_introduceM->add($data);
			}
			if($addres){
				$this->success('保存成功',U('AboutUs/company_introduce'));
			}else{
				$this->error('保存失败',U('AboutUs/company_introduce'));
			}
			exit;
		}
		$navall=$this->selnav();
		$this->assign('navres',$navall[0]);
		$this->assign('navarr',$navall[1]);
		$this->display();
	}
	//================================================================
	//修改公司简介信息
	public function company_introduce_update(){
		if($_POST){
			$company_introduceM=D('company_introduce');
			$whereAA['ci_id']=1;
			$data['ci_name']=I('post.ci_name');
			$data['ci_content']=I('post.ci_content','',false);
			$data['ci_content_english']=I('post.ci_content_english','',false);
			$data['ci_logo']=I('post.ci_logo');
			$data['ci_year']=I('post.ci_year');
			$data['ci_url']=I('post.ci_url');
			$data['ci_logotitle']=I('post.ci_logotitle');
			
			$data['ci_logotitle_english']=I('post.ci_logotitle_english');
			$data['nav_id']=I('post.nav_id');
			$addres=$company_introduceM->where($whereAA)->save($data);
			if($addres){
				$this->success('保存成功',U('AboutUs/company_introduce'));
			}else{
				$this->error('保存失败',U('AboutUs/company_introduce'));
			}
			exit;
		}
		$company_introduceM=D('company_introduce');
		$whereci['ci_id']=1;
		$company_introduce=$company_introduceM->where($whereci)->find();
		$this->assign('company_introduce',$company_introduce);
        
        //查询修改信息包含的导航
        $navM=D('nav');
        $whereBB['nav_id']=$company_introduce['nav_id'];
        $navs=$navM->where($whereBB)->find();
        $this->assign('navs',$navs);
        //dump($navs);exit;
		//查询导航
		$navall=$this->selnav();
		$this->assign('navres',$navall[0]);
		$this->assign('navarr',$navall[1]);
		$this->display();
	}
	//================================================================
	//删除公司简介信息
	public function company_introduce_del(){
		$company_introduceM=D('company_introduce');
		$whereci['ci_id']=1;
		$delres=$company_introduceM->where($whereci)->delete();
		if($delres){
				$this->success('保存成功',U('AboutUs/company_introduce'));
			}else{
				$this->error('保存失败',U('AboutUs/company_introduce'));
			}
	}
	//============================================
	//关于维拉页面基本信息
	public function basedata(){
		$basedataM=D('basedata');
		//查询所有的导航信息基础信息
		$navM=D('nav');
		$wherename['nav_name']="关于薇拉";
		$navs=$navM->where($wherename)->find();
		//查询基本信息
		$wherebase['nav_id']=$navs['nav_id'];
		$basedata_res=$basedataM->where($wherebase)->select();
		$this->assign('basedata_res',$basedata_res);
		//查询包含的导航信息
		
		$navarr=array();
		for($i=0;$i<count($basedata_res);$i++){
            $whereAA['nav_id']=$basedata_res[$i]['nav_id'];
            $navres=$navM->where($whereAA)->find();
            $navarr[]=$navres;
		}
		$this->assign('navarr',$navarr);
		$this->display();
	}
	//=================================================
	//基本信息添加
	public function basedata_add(){
		if($_POST){
			$basedataM=D('basedata');
			$data['title1']=I('post.title1');
			$data['title2']=I('post.title2');
			$data['title3']=I('post.title3');
			$data['title4']=I('post.title4');
			$data['title5']=I('post.title5','',false);
			$data['sort']=I('post.sort');
			$data['nav_id']=I('post.nav_id');
			$addres=$basedataM->add($data);
			if($addres){
				$this->success('保存成功',U('AboutUs/basedata'));
			}else{
				$this->error('保存失败',U('AboutUs/basedata'));
			}
			exit;
		}
		$navall=$this->selnav();
		$this->assign('navres',$navall[0]);
		$this->assign('navarr',$navall[1]);
		$this->display();
	}
	//===================================================
	//修改基础信息
	public function basedata_update(){
		if($_POST){
			$basedataM=D('basedata');
			$whereAA['id']=I('post.id');
			$data['title1']=I('post.title1');
			$data['title2']=I('post.title2');
			$data['title3']=I('post.title3');
			$data['title4']=I('post.title4');
			$data['title5']=I('post.title5','',false);
			$data['sort']=I('post.sort');
			$data['nav_id']=I('post.nav_id');
			$saveres=$basedataM->where($whereAA)->save($data);
			if($saveres){
				$this->success('保存成功',U('AboutUs/basedata'));
			}else{
				$this->error('保存失败',U('AboutUs/basedata'));
			}
			exit;
		}
		$basedataM=D('basedata');
		$whereci['id']=I('get.id');
		$basedata=$basedataM->where($whereci)->find();
		$this->assign('basedata',$basedata);
        
        //查询修改信息包含的导航
        $navM=D('nav');
        $whereBB['nav_id']=$basedata['nav_id'];
        $navs=$navM->where($whereBB)->find();
        $this->assign('navs',$navs);
        //dump($navs);exit;
		//查询导航
		$navall=$this->selnav();
		$this->assign('navres',$navall[0]);
		$this->assign('navarr',$navall[1]);
		$this->display();
	}
	//查询导航
	public function selnav(){
		$navM=D('nav');
		//查询一级导航
		$whereAA['fid']=0;
		$navres=$navM->where($whereAA)->order('nav_sort')->select();
        
        //查询二级导航
        $navarr=array();
        for($i=0;$i<count($navres);$i++){
        	$whereBB['fid']=$navres[$i]['nav_id'];
        	$navsecond=$navM->where($whereBB)->select();
        	$navarr[]=$navsecond;
        }
        $navall=array();
        $navall[]=$navres;
        $navall[]=$navarr;
        return $navall;
	}

}
?>