<?php
namespace Admin\Controller;
use Think\Controller;
class CustomWordController extends CommonController{
	public function left(){
		$this->display();
	}
	//===================================================
	//政策法规分类
	public function custom_word_classify(){
		$p=I('get.p');
		$this->assign('p',$p);
		//查询分类
		$custom_word_classifyM=D('custom_word_classify');
		$custom_word_classify_res=$custom_word_classifyM->order('cwc_sort desc')->page($p,10)->select();
		$this->assign('custom_word_classify_res',$custom_word_classify_res);
		//dump($custom_word_classify_res);
		//获取总页数
		$custom_word_classify_count=$custom_word_classifyM->select();
		$allcount=count($custom_word_classify_count);
		$page=ceil($allcount/10);
		$this->assign('page',$page);
		$this->display();
	}
	//===================================================
	//添加政策分类
	public function custom_word_classify_add(){
		if($_POST){
			$custom_word_classifyM=D('custom_word_classify');
			$data['cwc_name']=I('post.cwc_name');
			$data['cwc_sort']=I('post.cwc_sort');
			$addres=$custom_word_classifyM->add($data);
			if($addres){
				$this->success('保存成功',U('CustomWord/custom_word_classify'));
			}else{
				$this->error('保存失败',U('CustomWord/custom_word_classify'));
			}
			exit;
		}
		$this->display();
	}
	//====================================================
	//修改政策分类
	public function custom_word_classify_update(){
		if($_POST){
			$custom_word_classifyM=D('custom_word_classify');
			$whereBB['cwc_id']=I('post.cwc_id');
			$data['cwc_name']=I('post.cwc_name');
			$data['cwc_sort']=I('post.cwc_sort');
			$saveres=$custom_word_classifyM->where($whereBB)->save($data);
			if($saveres){
				$this->success('保存成功',U('CustomWord/custom_word_classify'));
			}else{
				$this->error('保存失败',U('CustomWord/custom_word_classify'));
			}
			exit;
		}
		$custom_word_classifyM=D('custom_word_classify');
		$whereAA['cwc_id']=I('get.cwc_id');
		$custom_word_classify=$custom_word_classifyM->where($whereAA)->find();
		$this->assign('custom_word_classify',$custom_word_classify);
		$this->display();
	}
	//======================================================
	//删除政策分类
	public function custom_word_classify_del(){
		$custom_word_classifyM=D('custom_word_classify');
		$whereAA['cwc_id']=I('get.cwc_id');
		$delres=$custom_word_classifyM->where($whereAA)->delete();
		if($delres){
				$this->success('保存成功',U('CustomWord/custom_word_classify'));
			}else{
				$this->error('保存失败',U('CustomWord/custom_word_classify'));
			}
	}
	//=====================================================
	//政策文章
	public function custom_word(){
		$p=I('get.p');
		$this->assign('p',$p);
		//查询政策法规
		$custom_wordM=D('custom_word');
		$cwc_id=I('get.cwc_id');
		$whereAA['cwc_id']=I('get.cwc_id');
		$custom_word_res=$custom_wordM->where($whereAA)->order('cw_sort desc')->page($p,10)->select();
		$this->assign('cwc_id',$cwc_id);
        $this->assign('custom_word_res',$custom_word_res);
        //查询总页数
        $custom_word_count=$custom_wordM->where($whereAA)->select();
        $allcount=count($custom_word_count);
        $page=ceil($allcount/10);
        $this->assign('page',$page);
		$this->display();
	}
	//=====================================================
	//添加政策文章
	public function custom_word_add(){
		 $cwc_id=I('get.cwc_id');
		 $p=I('get.p');
         if($_POST){
			$custom_wordM=D('custom_word');
			$data['cw_name']=I('post.cw_name');
			$data['cw_content']=I('post.cw_content','',false);
			$data['cw_time']=time();
			$data['cw_user_rank']=I('post.cw_user_rank');
			$data['cw_word_rank']=I('post.cw_word_rank');
			$data['cw_image']=I('post.cw_image');
			$data['cw_flag']=I('post.cw_flag');
			$data['cw_kind']=I('post.cw_kind');
			$data['cw_sort']=I('post.cw_sort');
			$data['cwc_id']=$cwc_id;
			$addres=$custom_wordM->add($data);
			if($addres){
				$this->success('保存成功',U('CustomWord/custom_word',array('cwc_id'=>$cwc_id,'p'=>$p)));
			}else{
				$this->error('保存失败',U('CustomWord/custom_word',array('cwc_id'=>$cwc_id,'p'=>$p)));
			}
			exit;
		}
		$this->display();
	}
	//======================================================
	//修改政策文章
	public function custom_word_update(){
		$cwc_id=I('get.cwc_id');
		$p=I('get.p');
         if($_POST){
			$custom_wordM=D('custom_word');
			$whereAA['cw_id']=I('post.cw_id');
			$data['cw_name']=I('post.cw_name');
			$data['cw_content']=I('post.cw_content','',false);
			$data['cw_time']=time();
			$data['cw_user_rank']=I('post.cw_user_rank');
			$data['cw_word_rank']=I('post.cw_word_rank');
			$data['cw_image']=I('post.cw_image');
			$data['cw_flag']=I('post.cw_flag');
			$data['cw_kind']=I('post.cw_kind');
			$data['cw_sort']=I('post.cw_sort');
			$data['cwc_id']=$cwc_id;
			$saveres=$custom_wordM->where($whereAA)->save($data);
			if($saveres){
				$this->success('保存成功',U('CustomWord/custom_word',array('cwc_id'=>$cwc_id,'p'=>$p)));
			}else{
				$this->error('保存失败',U('CustomWord/custom_word',array('cwc_id'=>$cwc_id,'p'=>$p)));
			}
			exit;
		}
		$custom_wordM=D('custom_word');
		$whereBB['cw_id']=I('get.cw_id');
		$custom_word=$custom_wordM->where($whereBB)->find();
		$this->assign('custom_word',$custom_word);
		$this->display();
	}
	//============================================================
	//删除政策文章信息
	public function custom_word_del(){
		$cwc_id=I('get.cwc_id');
		$p=I('get.p');
		$custom_wordM=D('custom_word');
		$whereBB['cw_id']=I('get.cw_id');
		$delres=$custom_wordM->where($whereBB)->delete();
		if($delres){
				$this->success('保存成功',U('CustomWord/custom_word',array('cwc_id'=>$cwc_id,'p'=>$p)));
			}else{
				$this->error('保存失败',U('CustomWord/custom_word',array('cwc_id'=>$cwc_id,'p'=>$p)));
			}
	}
	//==============================================
	//客户照片管理
	public function custom_image(){
		$p=I('get.p');
		$this->assign('p',$p);
		//查询政策法规
		$custom_imageM=D('custom_image');
		$cw_id=I('get.cw_id');
		$whereAA['cw_id']=I('get.cw_id');
		$custom_image_res=$custom_imageM->where($whereAA)->order('ci_sort desc')->page($p,10)->select();
		$this->assign('cw_id',$cw_id);
        $this->assign('custom_image_res',$custom_image_res);
        //dump($custom_image_res);
        //查询总页数
        $custom_image_count=$custom_imageM->where($whereAA)->select();
        $allcount=count($custom_image_count);
        $page=ceil($allcount/10);
        $this->assign('page',$page);
		$this->display();
	}
	//=======================================================
	//添加客户图片信息
	public function custom_image_add(){
		 $cw_id=I('get.cw_id');
		 $p=I('get.p');
         if($_POST){
			$custom_imageM=D('custom_image');
			$data['ci_name']=I('post.ci_name');
			$data['ci_sort']=I('post.ci_sort');
			$data['cw_id']=$cw_id;
			$addres=$custom_imageM->add($data);
			if($addres){
				$this->success('保存成功',U('CustomWord/custom_image',array('cw_id'=>$cw_id,'p'=>$p)));
			}else{
				$this->error('保存失败',U('CustomWord/custom_image',array('cw_id'=>$cw_id,'p'=>$p)));
			}
			exit;
		}
		$this->display();
	}
	//修改客户图片信息
	public function custom_image_update(){
		 $cw_id=I('get.cw_id');
		 $p=I('get.p');
         if($_POST){
			$custom_imageM=D('custom_image');
			$whereAA['ci_id']=I('post.ci_id');
			$data['ci_name']=I('post.ci_name');
			$data['ci_sort']=I('post.ci_sort');
			$data['cw_id']=$cw_id;
			$addres=$custom_imageM->where($whereAA)->save($data);
			if($addres){
				$this->success('保存成功',U('CustomWord/custom_image',array('cw_id'=>$cw_id,'p'=>$p)));
			}else{
				$this->error('保存失败',U('CustomWord/custom_image',array('cw_id'=>$cw_id,'p'=>$p)));
			}
			exit;
		}
		//查询需要修改的信息
		$custom_imageM=D('custom_image');
		$whereBB['ci_id']=I('get.ci_id');
		$custom_image=$custom_imageM->where($whereBB)->find();
		$this->assign('custom_image',$custom_image);
		$this->display();
	}
	//=======================================================
	//删除客户照片信息
	public function custom_image_del(){
		 $cw_id=I('get.cw_id');
		 $p=I('get.p');
		$custom_imageM=D('custom_image');
		$whereBB['ci_id']=I('get.ci_id');
		$delres=$custom_imageM->where($whereBB)->delete();
		if($delres){
				$this->success('保存成功',U('CustomWord/custom_image',array('cw_id'=>$cw_id,'p'=>$p)));
			}else{
				$this->error('保存失败',U('CustomWord/custom_image',array('cw_id'=>$cw_id,'p'=>$p)));
			}
	}
	//查询导航
	public function selnav(){
		$navM=D('nav');
		//查询一级导航
		$whereAA['fid']=0;
		$navres=$navM->where($whereAA)->order('nav_sort')->select();
        
        //查询二级导航
        $navarr=array();
        for($i=0;$i<count($navres);$i++){
        	$whereBB['fid']=$navres[$i]['nav_id'];
        	$navsecond=$navM->where($whereBB)->select();
        	$navarr[]=$navsecond;
        }
        $navall=array();
        $navall[]=$navres;
        $navall[]=$navarr;
        return $navall;
	}
}
?>